### ISSUE TITLE
Essential features to add

### ISSUE THREAD

**Issue by mazzmn** [SaturnGrandRapids/career-demo-bot-soft#12]
Need to get set up with a wireless router --done

Need to have the buttons and comparability with phones/tablets especially need to check with apple for sure (done well this is issue #8 and it is being worked)

Need to have Mongo Db installed on everyone's box who wants to test it --done

Need a way to ensure the right person wins a prize..so name on leader, and secret word 
Need to clean the maze off the beginning...just have a Play button and enter username, password
We want to enforce uniqueness on the db of the User Name, so only one Tom can be in the db for example --done

db will contain:  Unique Username/socket id/gamescore score/round --done

Current round leaders should be shown on the dashboard...and we should also all time leaders as well as the winners of each rounds..so Current Leaders, Round Leaders and All Time Leaders (may need to rotate or have a button to switch it). this is issue 10 and is being worked 

Need to have the dashboard have mazes next to each other
should we autoscale or at least shrink the size of the mazes on the dashboard --done (for the most part)

Need an admin page so we can see the secret codes and we can update the current round..plus we might want to keep track of whether they got "fed" their candy bar or not --done

Need to go thru the CSS and clean up the colors of all the buttons and so forth (ie today the start and quit button are a different font color that some of the other fonts) --done

No need to have columns that can be sorted in the leader board (ie what if I want to sort by name so I can find what my score is without scrolling thru everything) --not going to do

Should have a way to show just the Results without seeing the dashboard --done (admin page)

Should have a way to have the header of the page should persist...ie it should say at least Dashboard before the game is running....game starting soon.... --done

Can't have stale games on the dashboard...there is already a ticket open for this --done

Main Happypath workflow
1 have a posterboard that says go to this wireless router and join ...then go to this URL
(should we have a domain server on our router so the URL is saturnsys.com/game or something??
2 user sees screen that just has the name and a big play button
3 the go to the maze and press another start button
4 solve mazes until their time is up
5 when they get done...message that says congrats you finished with xxx score and are currently xxx in this round
6 would you like to play again or quit  (if they say play again we can bypass the login screen and go to the maze that is why we need to start button)...if they say quit then we go to the login screen.

**Comment by nathansmetelak** [comment]
@mazzmn 

I've updated your commetns.  It's at a point where you should go back thrugh these and create individual issues and assign them out to those who will be working on them.

**Comment by mazzmn** [comment]
updated the comment, I think we covered all the ones we want to cover except for the 2 still being worked on via other issues (dashboard and buttons for tablets)
