### ISSUE TITLE
Clean up start and maze page

### ISSUE THREAD

**Issue by nathansmetelak** [SaturnGrandRapids/career-demo-bot-soft#14]
They look like crap, let's get them cleaned up.

**Comment by nathansmetelak** [comment]
Maze is starting to look a lot nicer.  Nice work @prethishmathew.  Now we just need to get the start page better.  My biggest problem with it is that you have to click that start link.  I would rather it trigger off the enter key and whatnot.

**Comment by mazzmn** [comment]
Made the start page have consistent icons, added small margins, moved help button to the right and made the enter key work
