### ISSUE TITLE
Add Scoreboard page

### ISSUE THREAD

**Issue by nathansmetelak** [SaturnGrandRapids/career-demo-bot-soft#4]
As a group of users, i want a scoreboard to show all of the scores of the people competing

**Comment by mazzmn** [comment]
Ryan and I were talking about this...for starters, the game score is being passed on the game update message so we display the score on the dashboard
But, we thought maybe we should have a separate page...Hall of Fame and each time a game ends, then a new entry is added to that page....Player and Score (indexed by the socket.id) ordered with highest scores at the top...sound right??  This could be done by monitoring the game over socket msg. Note: If the server ends the list of users and scores will be lost

**Comment by nathansmetelak** [comment]
I've added /admin that shows all of the scores from everyone who has played during that runtime, with a dropdown to go through on a per round basis.

Also added the ability to notify who you gave a prize to.
